### ISSUE TITLE
Code is different from the paper ?

### ISSUE THREAD

**Issue by Slonna** [onceCWJ/FCDNet#1]
It seems that there is a big difference between the code and the paper, such as the identical ShortAdj_generator & LongAdj_generator

**Comment by onceCWJ** [comment]
The code and paper are consistent, as you mentioned ShortAdj_ Generator and LongAdj_Generator are different. The two correspond to the information extraction of LTFE in the dimensions of P and S in the paper, so the codes are quite similar
